[project]
name = "17-adv-rishta-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai-agents>=0.2.4",
    "python-dotenv>=1.1.1",
    "reportlab>=4.4.3",
    "streamlit>=1.48.0",
]
